//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDCAPP.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDCAPP.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the application.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support the project.
        /// </summary>
        internal static string Adblock {
            get {
                return ResourceManager.GetString("Adblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support the project. Turn off advertising in the application..
        /// </summary>
        internal static string AdblockAbout {
            get {
                return ResourceManager.GetString("AdblockAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogues:.
        /// </summary>
        internal static string Analog {
            get {
                return ResourceManager.GetString("Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog of drilling equipment and materials.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer.
        /// </summary>
        internal static string AuthorApp {
            get {
                return ResourceManager.GetString("AuthorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andrey Ovcharenko.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorship.
        /// </summary>
        internal static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        internal static string CalcButtonLab {
            get {
                return ResourceManager.GetString("CalcButtonLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density, g/cm3:.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base density:.
        /// </summary>
        internal static string DensityBaseLabel {
            get {
                return ResourceManager.GetString("DensityBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base density.
        /// </summary>
        internal static string DensityBaseTitle {
            get {
                return ResourceManager.GetString("DensityBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density, kg/m3:.
        /// </summary>
        internal static string DensityCalcLabel {
            get {
                return ResourceManager.GetString("DensityCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density:.
        /// </summary>
        internal static string DensityLabel {
            get {
                return ResourceManager.GetString("DensityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metod to correct density:.
        /// </summary>
        internal static string DensityMetodLabel {
            get {
                return ResourceManager.GetString("DensityMetodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density at a given temperature, kg/m3.
        /// </summary>
        internal static string DensityResultLabel {
            get {
                return ResourceManager.GetString("DensityResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density.
        /// </summary>
        internal static string DensityTitle {
            get {
                return ResourceManager.GetString("DensityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel:.
        /// </summary>
        internal static string EnergyLabel {
            get {
                return ResourceManager.GetString("EnergyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature:.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter by type.
        /// </summary>
        internal static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formula:.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data is incorrect or missing!.
        /// </summary>
        internal static string FormulaError {
            get {
                return ResourceManager.GetString("FormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function:.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standards:.
        /// </summary>
        internal static string GOST {
            get {
                return ResourceManager.GetString("GOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grade:.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group:.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amt.
        /// </summary>
        internal static string HeaderAmt {
            get {
                return ResourceManager.GetString("HeaderAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogues.
        /// </summary>
        internal static string HeaderAnalog {
            get {
                return ResourceManager.GetString("HeaderAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature.
        /// </summary>
        internal static string HeaderFeature {
            get {
                return ResourceManager.GetString("HeaderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature.
        /// </summary>
        internal static string HeaderFeature1 {
            get {
                return ResourceManager.GetString("HeaderFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function.
        /// </summary>
        internal static string HeaderFunction {
            get {
                return ResourceManager.GetString("HeaderFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standards.
        /// </summary>
        internal static string HeaderGOST {
            get {
                return ResourceManager.GetString("HeaderGOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight,
        ///kg/m.
        /// </summary>
        internal static string HeaderMassM {
            get {
                return ResourceManager.GetString("HeaderMassM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass,
        ///kg.
        /// </summary>
        internal static string HeaderMassPcs {
            get {
                return ResourceManager.GetString("HeaderMassPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        internal static string HeaderNote {
            get {
                return ResourceManager.GetString("HeaderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type pipes.
        /// </summary>
        internal static string HeaderTypePipes {
            get {
                return ResourceManager.GetString("HeaderTypePipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Picture:.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на inch.
        /// </summary>
        internal static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount:.
        /// </summary>
        internal static string labelAmt {
            get {
                return ResourceManager.GetString("labelAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string labVersion {
            get {
                return ResourceManager.GetString("labVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LanguageEng {
            get {
                return ResourceManager.GetString("LanguageEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string LanguageRus {
            get {
                return ResourceManager.GetString("LanguageRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language.
        /// </summary>
        internal static string LanguagesApp {
            get {
                return ResourceManager.GetString("LanguagesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Application Language.
        /// </summary>
        internal static string LanguagesSelect {
            get {
                return ResourceManager.GetString("LanguagesSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight, kg/m:.
        /// </summary>
        internal static string MassM {
            get {
                return ResourceManager.GetString("MassM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass, kg:.
        /// </summary>
        internal static string MassPcs {
            get {
                return ResourceManager.GetString("MassPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass, tons:.
        /// </summary>
        internal static string MassT {
            get {
                return ResourceManager.GetString("MassT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string messageAttention {
            get {
                return ResourceManager.GetString("messageAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to delete the item?.
        /// </summary>
        internal static string messageDelete {
            get {
                return ResourceManager.GetString("messageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to exit this App?.
        /// </summary>
        internal static string messageExit {
            get {
                return ResourceManager.GetString("messageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid data entry format!.
        /// </summary>
        internal static string messageFormatError {
            get {
                return ResourceManager.GetString("messageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing the language requires that Drilling eCatalog be restarted!.
        /// </summary>
        internal static string messageLanguage {
            get {
                return ResourceManager.GetString("messageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This entry already exists!.
        /// </summary>
        internal static string messageNewItem {
            get {
                return ResourceManager.GetString("messageNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No active recording!.
        /// </summary>
        internal static string messageNoActiveRecord {
            get {
                return ResourceManager.GetString("messageNoActiveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string messageOk {
            get {
                return ResourceManager.GetString("messageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success!.
        /// </summary>
        internal static string messageSuccess {
            get {
                return ResourceManager.GetString("messageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Action!.
        /// </summary>
        internal static string messageTitleAction {
            get {
                return ResourceManager.GetString("messageTitleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit App?.
        /// </summary>
        internal static string messageTitleExit {
            get {
                return ResourceManager.GetString("messageTitleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string messageСancel {
            get {
                return ResourceManager.GetString("messageСancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from the observed density at the base temperature to the desired.
        /// </summary>
        internal static string metricBaseLabel {
            get {
                return ResourceManager.GetString("metricBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from density at observed temperature to basic conditions.
        /// </summary>
        internal static string metricObservedLabel {
            get {
                return ResourceManager.GetString("metricObservedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mm.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect to your account!.
        /// </summary>
        internal static string NoConnected {
            get {
                return ResourceManager.GetString("NoConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes:.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application on other platforms.
        /// </summary>
        internal static string OSAbout {
            get {
                return ResourceManager.GetString("OSAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel Density Calculation in Google Play.
        /// </summary>
        internal static string OSAndroid {
            get {
                return ResourceManager.GetString("OSAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel Density Calculation in Microsoft Store.
        /// </summary>
        internal static string OSMicrosoft {
            get {
                return ResourceManager.GetString("OSMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application does not collect or store any user information..
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy.
        /// </summary>
        internal static string PrivacyApp {
            get {
                return ResourceManager.GetString("PrivacyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy Statement.
        /// </summary>
        internal static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate the app.
        /// </summary>
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsApp {
            get {
                return ResourceManager.GetString("SettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table:.
        /// </summary>
        internal static string TableSymbolLabel {
            get {
                return ResourceManager.GetString("TableSymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        internal static string TableSymbolTitle {
            get {
                return ResourceManager.GetString("TableSymbolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base temperature, °С:.
        /// </summary>
        internal static string TempBaseCalcLabel {
            get {
                return ResourceManager.GetString("TempBaseCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base t°С:.
        /// </summary>
        internal static string TempBaseLabel {
            get {
                return ResourceManager.GetString("TempBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base t°С.
        /// </summary>
        internal static string TempBaseTitle {
            get {
                return ResourceManager.GetString("TempBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature, °С:.
        /// </summary>
        internal static string TempCalcLabel {
            get {
                return ResourceManager.GetString("TempCalcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the application theme.
        /// </summary>
        internal static string ThemesApp {
            get {
                return ResourceManager.GetString("ThemesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string ThemesDarkName {
            get {
                return ResourceManager.GetString("ThemesDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string ThemesLightName {
            get {
                return ResourceManager.GetString("ThemesLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string ThemesOSName {
            get {
                return ResourceManager.GetString("ThemesOSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel density calculation.
        /// </summary>
        internal static string TitleCalcCement {
            get {
                return ResourceManager.GetString("TitleCalcCement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In development!.
        /// </summary>
        internal static string TitleDevelopment {
            get {
                return ResourceManager.GetString("TitleDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element Catalogue.
        /// </summary>
        internal static string TitleElementCatalog {
            get {
                return ResourceManager.GetString("TitleElementCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element Groups.
        /// </summary>
        internal static string TitleElementGroup {
            get {
                return ResourceManager.GetString("TitleElementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel.
        /// </summary>
        internal static string TitleEnergy {
            get {
                return ResourceManager.GetString("TitleEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuels groups.
        /// </summary>
        internal static string TitleEnergyType {
            get {
                return ResourceManager.GetString("TitleEnergyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel density.
        /// </summary>
        internal static string TitleFuelCalc {
            get {
                return ResourceManager.GetString("TitleFuelCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density calculation.
        /// </summary>
        internal static string TitleFuelDenCalc {
            get {
                return ResourceManager.GetString("TitleFuelDenCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Density table.
        /// </summary>
        internal static string TitleFuelDenTable {
            get {
                return ResourceManager.GetString("TitleFuelDenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel types.
        /// </summary>
        internal static string TitleFuelType {
            get {
                return ResourceManager.GetString("TitleFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string TitleMasterPage {
            get {
                return ResourceManager.GetString("TitleMasterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species.
        /// </summary>
        internal static string TitleRockRang {
            get {
                return ResourceManager.GetString("TitleRockRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  tons.
        /// </summary>
        internal static string Tonn {
            get {
                return ResourceManager.GetString("Tonn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string ToolbarItemFilter {
            get {
                return ResourceManager.GetString("ToolbarItemFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type pipe:.
        /// </summary>
        internal static string TypePipes {
            get {
                return ResourceManager.GetString("TypePipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database Version:.
        /// </summary>
        internal static string VersionDB {
            get {
                return ResourceManager.GetString("VersionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project site.
        /// </summary>
        internal static string WebApp {
            get {
                return ResourceManager.GetString("WebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something&apos;s wrong? Let me know .
        /// </summary>
        internal static string WrongLabel {
            get {
                return ResourceManager.GetString("WrongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In here.
        /// </summary>
        internal static string WrongLabelMail {
            get {
                return ResourceManager.GetString("WrongLabelMail", resourceCulture);
            }
        }
    }
}
